// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"go-example-api/app/api/controller"
	"go-example-api/app/domain/repository"
	"go-example-api/app/domain/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitAPI(db *gorm.DB) Initialization {
	userRepository := repository.ProvideUserRepository(db)
	userService := service.ProvideUserService(userRepository)
	userController := controller.ProvideUserController(userService)
	initialization := ProvideInitialization(userRepository, userService, userController)
	return initialization
}
